require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/BlockLength:
  ExcludedMethods:
    [
      'describe',
      'let',
      'it',
      'before',
      'context',
      'shared_examples',
      'factory',
      'define',
      'included',
    ]
