default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: shoppingcart
  password: password
  timeout: 5000

development:
  <<: *default
  database: shoppingcart_development
test:
  <<: *default
  database: shoppingcart_test

production:
  <<: *default
  database: shoppingcart
